//
// Created by Nick Clason on 3/9/21.
//

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/********
 * This file is the runtime for the language
 * It is linked to the file after the assembly is generated by my compiler.
 *******/

bool PUTINTEGER(int a) {
    printf("%i\n", a);
    return true;
}